# Names:
# dev-fs-spark-v3-dynamo-event-pipes

#######################################################
# Creates a local or global eventbridge bus
#######################################################

AWSTemplateFormatVersion: "2010-09-09"
Description: Content V3 EventBridge Pipe

Parameters:
  CloudformationTemplateSource:
    Description: The Cloudformation template source in the S3 bucket
    Type: String

  Environment:
    Description: Environment for deployment
    Type: String
    AllowedValues:
      - dev
      - stage
      - prod
      - poc
    Default: dev
    ConstraintDescription: Must be one of Dev, Stage, Prod, or POC.

  APIName:
    Description: The name of the business unit
    Type: String
    AllowedValues:
      - fs
      - fw
      - fb
      - fn
      - ok
    ConstraintDescription: Must be a supported BU Abbreviation (fs, fw, fb, fn, ok)

Resources:
  PipeIAMRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - pipes.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Policies:
        - PolicyName: DynamoDBPipeSource
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:DescribeStream
                  - dynamodb:GetRecords
                  - dynamodb:GetShardIterator
                  - dynamodb:ListStreams
                  - dynamodb:BatchGetItem
                  - dynamodb:GetItem
                Resource:
                  - Fn::ImportValue:
                      'Fn::Sub': "${Environment}-${APIName}-spark-v3-content-stream-arn"
        - PolicyName: EventBusPipeTarget
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - events:PutEvents
                Resource:
                  - Fn::ImportValue:
                      'Fn::Sub': "${Environment}-${APIName}-spark-v3-local-event-bus-arn"

        - PolicyName: CloudWatchLogging
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource:
                  !Sub "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/*"

  V3ContentPipeLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/vendedlogs/${Environment}-${APIName}-spark-v3-content-event-bus-pipe"
      RetentionInDays: 7

  V3ContentPipe:
    Type: AWS::Pipes::Pipe
    Properties:
      Description: >-
        Pipe spark v3 content dynamo table stream events to the local event bus
      Name: !Sub "${Environment}-${APIName}-spark-v3-content-event-bus-pipe"
      RoleArn:
        'Fn::GetAtt':
          - PipeIAMRole
          - Arn
      Source:
        Fn::ImportValue:
          'Fn::Sub': "${Environment}-${APIName}-spark-v3-content-stream-arn"
      SourceParameters:
        DynamoDBStreamParameters:
          StartingPosition: LATEST
      Target:
        Fn::ImportValue:
          'Fn::Sub': "${Environment}-${APIName}-spark-v3-local-event-bus-arn"

      LogConfiguration:
        Level: INFO
        CloudwatchLogsLogDestination:
          LogGroupArn:
            'Fn::GetAtt':
              - V3ContentPipeLogGroup
              - Arn
