AWSTemplateFormatVersion: "2010-09-09"

Description: Event Bridge Bus Rules Creation

Parameters:
  CloudformationTemplateSource:
    Description: The Cloudformation template source in the S3 bucket
    Type: String

  PrimaryControlBucket:
    Description: Primary region control bucket SSM Parameter reference
    Type: AWS::SSM::Parameter::Value<String>
    Default: /infrastructure/control_bucket

  Environment:
    Description: Environment for deployment
    Type: String
    AllowedValues:
      - dev
      - stage
      - prod
      - poc
    Default: dev
    ConstraintDescription: Must be one of Dev, Stage, Prod, or POC.

  Scope:
    Description: The scope of the bus
    Type: String
    AllowedValues:
      - local
      - global
    Default: local
    ConstraintDescription: Must be one of local, global

  APIName:
    Description: The name of the business unit
    Type: String
    AllowedValues:
      - fs
      - fw
      - fb
      - fn
      - ok
      - gen
      - et
    ConstraintDescription: Must be a supported BU Abbreviation (fs, fw, fb, fn, ok, gen, et)

Mappings:
  AWSAccounts:
    Fn::Transform:
      Name: AWS::Include
      Parameters:
        Location: !Sub "s3://${PrimaryControlBucket}/formation/include/AWSAccounts.json"

Resources:
  GlobalEventPublishRule:
    Type: 'AWS::Events::Rule'
    Properties:
      Name: !Sub "${Environment}-${APIName}-spark-v3-dynamo-global-publish-rule"
      Description: Routes to us-east-1 global event bus
      EventBusName: arn:aws:events:us-east-1:684424026845:event-bus/dev-fs-spark-v3-local-event-bus
      State: ENABLED
      EventPattern:
        source:
          - aws.dynamodb
      Targets:
        - Arn: >-
            arn:aws:events:us-east-1:008971673418:event-bus/dev-gen-spark-v3-global-event-bus
          Id: 'GlobalEventBus'
          RoleArn: !GetAtt
            - EventBridgeIAMrole
            - Arn

  EventBridgeIAMrole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: !Sub events.amazonaws.com
            Action: 'sts:AssumeRole'
      Path: /
      Policies:
        - PolicyName: PutEventsDestinationBus
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - 'events:PutEvents'
                Resource:
                  - >-
                    arn:aws:events:us-east-1:008971673418:event-bus/dev-gen-spark-v3-global-event-bus