# Example Stack Names
# dev-et-spark-v3-eventbridge-publish-rule

#######################################################
# Creates a rule that publishes EventBridge bus events to a local BU
#######################################################

AWSTemplateFormatVersion: "2010-09-09"
Description: Spark V3 Eventbridge Bus BU Publish Rule

Parameters:
  CloudformationTemplateSource:
    Description: The Cloudformation template source in the S3 bucket
    Type: String

  Environment:
    Description: Environment for deployment
    Type: String
    AllowedValues:
      - dev
      - stage
      - prod
      - poc
    Default: dev
    ConstraintDescription: Must be one of Dev, Stage, Prod, or POC.

  APIName:
    Description: The name of the business unit
    Type: String
    AllowedValues:
      - fs
      - fw
      - fb
      - fn
      - ok
      - et
    ConstraintDescription: Must be a supported BU Abbreviation (fs, fw, fb, fn, ok, et)

  TargetBusARN: # todo: how can we make this more dynamic
    Description: The ARN of the local bus to publish events
    Type: String
    Default: arn:aws:events:us-east-1:954976311447:event-bus/dev-et-spark-v3-eventbridge-bus

Resources:
  EventBridgePublishRule:
    Type: 'AWS::Events::Rule'
    Properties:
      Name: !Sub "${Environment}-${APIName}-spark-v3-dynamo-${APIName}-publish-rule"
      Description: !Sub "Route Events to the ${APIName} local bus"
      EventBusName:
        'Fn::ImportValue':
          'Fn::Sub': "${Environment}-gen-spark-v3-event-bus-arn" # todo: importing the global event bus, could be better?

      State: ENABLED
      EventPattern:
        detail:
          eventSourceARN:
            - wildcard: "*spark-v3-content*" # todo: testing a specific source ARN (dynamodb table ARN)
      Targets:
        - Arn: !Sub "${TargetBusARN}"
          Id: !Sub "${APIName}LocalEventBus"
          RoleArn: !GetAtt
            - EventBridgeIAMrole
            - Arn

  EventBridgeIAMrole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: events.amazonaws.com
            Action: 'sts:AssumeRole'
      Path: /
      Policies:
        - PolicyName: PutEventsDestinationBus
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - 'events:PutEvents'
                Resource: !Sub "${TargetBusARN}"
